### ISSUE TITLE
return cleaning metrics in a csv (number hot, missing, diag, percent removed etc.) 

### ISSUE THREAD

**Issue by JoshuaBAtlas** [atlasxomics/clean_latch#5]
High priority

**Comment by jpmcga** [comment]
@JoshuaBAtlas modifications for incorporating changes with Latch:

1. In clean_task.py, update lines [56-59 ](https://github.com/atlasxomics/clean_latch/blob/d0e44f50c43907c0d8529ac5a6a0fcc8dace3660/wf/cleaning_task.py#L56-L59) to move both output files into a new dir, then return that as a `LatchDir`; update type hints to the function to return LatchDir.  See https://docs.latch.bio/basics/working_with_files.html

2. In __init__.py, import LatchDir, update function type hints and variable names to reflect change from LatchFile-> LatchDir.

3.  In upload_registry_task.py, update type hints  and variable names to reflect change from LatchFile-> LatchDir.

**Comment by jpmcga** [comment]
Resolved in MR #7
